services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build images
  - docker-compose -f docker-compose-build.yaml build --parallel
  
  # Tag images
  - docker tag reverseproxy:v1 victor494/reverseproxy
  - docker tag udagram-api-feed:v1 victor494/udagram-api-feed
  - docker tag udagram-api-user:v1 victor494/udagram-api-user
  - docker tag udagram-frontend:v1 victor494/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push victor494/reverseproxy
  - docker push victor494/udagram-api-feed
  - docker push victor494/udagram-api-user
  - docker push victor494/udagram-frontend